### PR TITLE
fix: BLAS batch strided needs sufficiently new MKL

### PR DESCRIPTION
**Pull request by hmenke**

### CODE REVIEW

**Comment by hmenke** [comment]
Just realized that there are no MKL tests in the CI, because I made a mistake in [the original commit](https://github.com/TRIQS/nda/commit/925d39025a3b14933242054cbab8f7848e7b14b7), yet the CI still passed.

**Comment by Wentzell** [comment]
Thank you @hmenke for adding this check.

I have enabled the `ubuntul-intel` builds in our Jenkins CI now also for nda.

**Comment by Wentzell** [comment]
Do you have a reference that shows that those functions were introduced in this specific version?

**Comment by hmenke** [comment]
I just guessed, because I noticed that it was present in 2020.4 but absent in 2020.0. Unfortunately it's not mentioned in the changelog when it was introduced so I just downloaded all past version from the repo and grepped through them, see the commit message.

**Review by Wentzell — APPROVED** [review]
Thank you @hmenke for this improvement!

**Comment by hmenke** [comment]
Please also cherry-pick this onto 1.2.x

**Comment by Wentzell** [comment]
> Please also cherry-pick this onto 1.2.x

Done

**Pull request merged**
